[package]
name = "pavao"
version = { workspace = true }
authors = { workspace = true }
build = "build.rs"
categories = ["network-programming"]
documentation = "https://docs.rs/pavao"
edition = { workspace = true }
homepage = "https://github.com/veeso/pavao"
include = [
  "src/**/*",
  "examples/**/*",
  "build.rs",
  "../docs/**/*",
  "../LICENSE",
  "../README.md",
  "../CHANGELOG.md",
]
keywords = { workspace = true }
license = { workspace = true }
readme = "../README.md"
repository = { workspace = true }
rust-version = { workspace = true }
description = "Rust client library for SMB 2/3 based on libsmbclient."
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
debug = []
no-log = ["log/max_level_off"]
vendored = ["pavao-sys/vendored"]

[dependencies]
lazy_static = { workspace = true }
libc = { workspace = true }
log = { workspace = true }
pavao-sys = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
argh = { workspace = true }
env_logger = { workspace = true }
pretty_assertions = { workspace = true }
rpassword = { workspace = true }
serial_test = { workspace = true }
testcontainers = { workspace = true, features = ["blocking"] }

[build-dependencies]
cfg_aliases = { workspace = true }

[lib]
name = "pavao"
path = "src/lib.rs"

[[example]]
name = "transfer"
path = "examples/transfer.rs"

[[example]]
name = "tree"
path = "examples/tree.rs"

[[example]]
name = "treeplus"
path = "examples/treeplus.rs"
