[package]
name = "pavao-sys"
version = { workspace = true }
authors = { workspace = true }
build = "build.rs"
categories = ["external-ffi-bindings", "network-programming"]
documentation = "https://docs.rs/pavao-sys"
edition = { workspace = true }
homepage = "https://github.com/veeso/pavao"
include = [
  "src/**/*",
  "build.rs",
  "../docs/**/*",
  "../LICENSE",
  "../README.md",
  "../CHANGELOG.md",
]
keywords = { workspace = true }
license = { workspace = true }
links = "smbclient"
readme = "../README.md"
repository = { workspace = true }
rust-version = { workspace = true }
description = "ffi bindings for libsmbclient. Use Pavao to access Samba shares from Rust."
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
vendored = ["dep:cc", "dep:pavao-src"]

[dependencies]
libc = { workspace = true }

[build-dependencies]
cc = { workspace = true, optional = true }
pavao-src = { workspace = true, optional = true }
pkg-config = { workspace = true }

[lib]
name = "pavao_sys"
path = "src/lib.rs"
