[package]
name = "pavao-src"
# This version tracks the bundled Samba release.
version = "4.22.0-4"
authors = { workspace = true }
categories = ["external-ffi-bindings", "network-programming"]
documentation = "https://docs.rs/pavao-src"
edition = { workspace = true }
homepage = "https://github.com/veeso/pavao"
include = ["src/**/*", "build.rs", "../docs/**/*", "../LICENSE", "README.md"]
keywords = { workspace = true }
license = { workspace = true }
readme = "README.md"
repository = { workspace = true }
rust-version = { workspace = true }
description = "Source of libsmbclient and logic to build vendored pavao."

[dependencies]
cc = { workspace = true }
git2 = { workspace = true, features = ["https"] }
glob = { workspace = true }

[lib]
name = "pavao_src"
path = "src/lib.rs"
